import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
import 'bootstrap-table/dist/bootstrap-table.min.css'
//import 'bootstrap-table/dist/themes/bootstrap-table/bootstrap-table.min.css'
import 'bootstrap-table/dist/extensions/sticky-header/bootstrap-table-sticky-header.min.css'
import 'bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css'
import 'bootstrap-select/dist/css/bootstrap-select.min.css'
import 'bootstrap-table/dist/extensions/page-jump-to/bootstrap-table-page-jump-to.min.css'
// import '../assets/bootstrap-table-jumpto.css'
import 'bootstrap-table/dist/extensions/filter-control/bootstrap-table-filter-control.min.css'

//import 'bootstrap-table/dist/themes/materialize/bootstrap-table-materialize.min.css'
import './jquery.js'
import Vue from 'vue'
import 'bootstrap'
import 'tableexport.jquery.plugin/libs/FileSaver/FileSaver.min.js'
import 'tableexport.jquery.plugin/tableExport.min.js'
import 'bootstrap-table/dist/bootstrap-table'
import BootstrapTable from 'bootstrap-table/dist/bootstrap-table-vue.esm'
//import 'bootstrap-table/dist/themes/bootstrap-table/bootstrap-table.min'
import 'bootstrap-table/dist/extensions/mobile/bootstrap-table-mobile.min'
import 'bootstrap-table/dist/extensions/page-jump-to/bootstrap-table-page-jump-to.min'
import 'bootstrap-table/dist/locale/bootstrap-table-zh-CN.js'
//import 'bootstrap-table/dist/themes/materialize/bootstrap-table-materialize.js'
import 'bootstrap-table/dist/extensions/export/bootstrap-table-export'
import 'bootstrap-table/dist/extensions/sticky-header/bootstrap-table-sticky-header.min'
import 'bootstrap-datepicker/dist/js/bootstrap-datepicker.min'
import 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min'
import 'bootstrap-select/dist/js/bootstrap-select.min'
import 'bootstrap-select/dist/js/i18n/defaults-zh_CN'
import '../assets/bootstrap-table-jumpto'
import 'bootstrap-table/dist/extensions/filter-control/bootstrap-table-filter-control.min'

Vue.component('BootstrapTable', BootstrapTable)
